---
# https://sc1.checkpoint.com/documents/R81.10/WebAdminGuides/EN/CP_R81.10_Maestro_AdminGuide/Topics-Maestro-AG/Upgrading-Maestro-with-CPUSE.htm?tocpath=Upgrading%20Maestro%20to%20R81.10%7C_____1
# add snapshot R8030SPa06 desc 06-install_JHF
- name: "Step 6 - Install the required Take of the Jumbo Hotfix Accumulator"
  hosts: sg
  gather_facts: false

  tasks:

### Prepare and clean

    - name: "Timestamp / Start Step 6 - Install the required Take of the Jumbo Hotfix Accumulator"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    - name: "remove usermode coredumps if exist"
      shell: g_all -a rm /var/log/dump/usermode/*
      changed_when: false

    - name: "core_dump_verifier -v"
      shell: core_dump_verifier -v
      changed_when: false
      register: res

    - name: "Debug / coredumps"
      debug: msg="{{ res.stdout_lines }}"
      when: loglevel>=2

    - name: "fix trailing spaces in cp-release" # must be already done, but...
      shell: g_all -a "sed -i 's/[ \t]*$//' /etc/cp-release"
      changed_when: false

    - name: "Translation result"
      shell: set -o pipefail && g_all -a "echo '|$(cat /etc/cp-release)|'"
      changed_when: false
      register: res
      when: loglevel>=2

    - name: "Debug / No trailing spaces"
      debug: msg="{{ res.stdout_lines }}"
      when: loglevel>=2


### Ensure smo auto-clone off

    - name: "Check number of smo image auto-clone on"
      shell: gexec -a -c 'clish -c "show smo image auto-clone state"' | grep -c "is on"
      register: res_no
      ignore_errors: true
      changed_when: false

    - name: "Make auto-clone off"
      block:
        - name: "Get list of SGMs with smo image auto-clone on"
          shell: gexec -a -c 'clish -c "show smo image auto-clone state"' | grep "is on"
          register: res
          ignore_errors: true
          changed_when: false

        - name: "Set auto_clone_smo"
          set_fact:
            auto_clone_smo: "{{ res.stdout_lines }}"

        - name: "Debug / smo image auto_clone on"
          debug:
            msg:
              - "Check and set back auto-clone state to ON when needed"
              - "{{ auto_clone_smo }}"
              - "I turn them OFF for upgrades"

        - name: "set smo image auto-clone off"
          shell: gclish -c "set smo image auto-clone state off"
          register: res
          ignore_errors: true
          changed_when: false

        - name: "Debug / set smo image auto-clone off"
          debug: msg="{{ res.stdout_lines }}"

      when: res_no.stdout | int > 0


### Start installation

    - name: "Install JHF on B"
      include_tasks: include/06-install_JHF.yml
      vars:
        logical_member: "{{ logicalBmember }}"
        logical_range: "{{ logicalBrange }}"
        is_first: true # validate on all SGMs

    - name: "Timestamp / Installed on B (06-install_JHF_BA.yml)"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    # ! I prefer more waiting
    # as console at B doesn't show login prompt when B becomes ACTIVE
    # potential performance degradation?

    - name: "Install JHF on A"
      include_tasks: include/06-install_JHF.yml
      vars:
        logical_member: "{{ logicalAmember }}"
        logical_range: "{{ logicalArange }}"
        is_first: false # validate only on specifed range

    - name: "Timestamp / Installed on A (06-install_JHF_BA.yml)"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

# tail -f /opt/CPInstLog/DeploymentAgent.log
# watch -n 2 asg stat -i sgm_info
# watch -n 2 'asg stat -i proc | grep -A 5 "SGM ID"'
