---
# https://sc1.checkpoint.com/documents/R81.10/WebAdminGuides/EN/CP_R81.10_Maestro_AdminGuide/Topics-Maestro-AG/Upgrading-Maestro-with-CPUSE.htm?tocpath=Upgrading%20Maestro%20to%20R81.10%7C_____1
# add snapshot R8030SPa06 desc 06-install_JHF
- name: "Step 6 - Install the required Take of the Jumbo Hotfix Accumulator"
  hosts: sg
  gather_facts: false

  tasks:

### Prepare and clean

    - name: "remove usermode coredumps if exist"
      raw: g_all -a rm /var/log/dump/usermode/*
      changed_when: false

    - name: "core_dump_verifier -v"
      raw: core_dump_verifier -v
      changed_when: false
      register: res

    - name: "Debug / coredumps"
      debug: msg="{{ res.stdout_lines }}"
      when: loglevel>=2

    - name: "fix trailing spaces in cp-release" # must be already done, but...
      raw: g_all -a "sed -i 's/[ \t]*$//' /etc/cp-release"
      changed_when: false

    - name: "Translation result"
      raw: g_all -a "echo '|$(cat /etc/cp-release)|'"
      changed_when: false
      register: res
      when: loglevel>=2

    - name: "Debug / No trailing spaces"
      debug: msg="{{ res.stdout_lines }}"
      when: loglevel>=2


### Start installation

    - name: "Install JHF on B"
      include_tasks: include/06-install_JHF.yml
      vars:
        logical_member: "{{ logicalBmember }}"
        logical_range: "{{ logicalBrange }}"
        is_first: true # validate on all SGMs

    - name: "Timestamp / Installed on B"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    - name: "Install JHF on A"
      include_tasks: include/06-install_JHF.yml
      vars:
        logical_member: "{{ logicalAmember }}"
        logical_range: "{{ logicalArange }}"
        is_first: false # validate only on specifed range

    - name: "Timestamp / Installed on A"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

  # - name: "Temporary stop"
  #   meta: end_play

# tail -f /opt/CPInstLog/DeploymentAgent.log
# watch -n 2 asg stat -i sgm_info
# watch -n 2 'asg stat -i proc | grep -A 5 "SGM ID"'
