---
# https://sc1.checkpoint.com/documents/R81.10/WebAdminGuides/EN/CP_R81.10_Maestro_AdminGuide/Topics-Maestro-AG/Upgrading-Maestro-with-CPUSE.htm?tocpath=Upgrading%20Maestro%20to%20R81.10%7C_____1
- name: "Step 7 - Upgrade the CPUSE Deployment Agent on the Security Group"
  hosts: sg
  gather_facts: false

  tasks:


### Update DA
    # - name: "Step 7 - Download Deployment Agent to local repo"
    #   get_url:
    #     url: "{{ remote_repo }}/{{ da_R80 }}"
    #     dest: "{{ local_repo }}"
    #     mode: 0644

    - name: "Timestamp / Start Step 7 - Upgrade the CPUSE Deployment Agent on the Security Group"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    - name: "Step 7 - Upload Deployment Agent to local repo on SMO"
      delegate_to: 127.0.0.1
      shell: |
        sshpass -p "{{ ansible_ssh_pass }}" sftp "{{ ansible_ssh_user }}@{{ groups.sg[0] }}" <<EOF
        lcd "{{ host_repo }}"
        cd "{{ local_repo }}"
        put "{{ package_name }}"
        quit
        EOF
      changed_when: false
      vars:
        package_name: "{{ da_R80 }}"

    - name: "Update Deployment Agent"
      shell: update_sp_da "{{ local_repo }}/{{ da_R80 }}"
      register: res
      changed_when: false

    - name: "Debug / Update Deployment Agent (07-upgrade_DA_on_sg.yml)"
      debug: msg="{{ res.stdout_lines }}"
      when: loglevel>0

    - name: "Deployment Agent status build"
      shell: gclish -c "show installer status build"
      register: res_status
      ignore_errors: true
      changed_when: false

    - name: "Debug / Deployment Agent status build (07-upgrade_DA_on_sg.yml)"
      debug: msg="{{ res_status.stdout_lines }}"
