---
# https://sc1.checkpoint.com/documents/R81.10/WebAdminGuides/EN/CP_R81.10_Maestro_AdminGuide/Topics-Maestro-AG/Upgrading-Maestro-with-CPUSE.htm?tocpath=Upgrading%20Maestro%20to%20R81.10%7C_____1
- name: "Step 8 -  Import the R81.10 upgrade package on the Security Group"
  hosts: sg
  gather_facts: no

  tasks:


### Import package

    - name: "Debug / Prepare to import package"
      debug: msg="Prepare to import package {{ pkg_upgrade_R81 }}"
      when: loglevel>0

    - name: "Timestamp / Start importing package"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    - name: "Import package"
      include_tasks: include/import_package.yml
      vars:
        package_name: "{{ pkg_upgrade_R81 }}"

    - name: "Show imported packages"
      shell: gclish -c "show installer packages imported"
      register: res
      changed_when: false
      # da_cli packages_info status=available_for_install

    - name: "Debug / Show imported packages"
      debug: msg="{{ res.stdout_lines }}"
      when: loglevel>=2

    # ! Find package index

    - name: "Timestamp / After importing package"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    - name: "Verify installer"
      shell: gclish -c "installer verify 1" | tail -15
      register: res_verify
      changed_when: false

    - name: "Check if all required SGMs allowed"
      shell: "echo {{ res_verify.stdout_lines }} | grep -v -i 'not'"
      register: res
      changed_when: false
      ignore_errors: true

    - name: "Verify installer failed - break!"
      fail:
        msg:
          - "Oops. Already installed? Not in sync? Break installation."
          - "{{ res_verify.stdout_lines }}"
      when: res.rc == 1
      # ! Need better error handling ?

    - name: "Debug / Verify installer - OK"
      debug:
        msg: "{{ res_verify.stdout_lines }}"
      when: res.rc == 0
