---
# https://sc1.checkpoint.com/documents/R81.10/WebAdminGuides/EN/CP_R81.10_Maestro_AdminGuide/Topics-Maestro-AG/Upgrading-Maestro-with-CPUSE.htm?tocpath=Upgrading%20Maestro%20to%20R81.10%7C_____1
- name: "Step 8 -  Import the R81.10 upgrade package on the Security Group"
  hosts: sg
  gather_facts: false

  tasks:

    - name: "Timestamp / Start Step 8 - Import the R81.10 upgrade package on the Security Group"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    - name: "Import package"
      include_tasks: include/import_package.yml
      vars:
        package_name: "{{ pkg_upgrade_R81 }}"

### Validate for memberA and memberB
# Import to the specific member if needed (very rare, but...)

    - name: "Get pkg_index on A"
      include_tasks: include/get_pkg_index.yml
      vars:
        package_file_name: "{{ pkg_upgrade_R81 }}"
        logical_member: "{{ logicalAmember }}"

    - name: "Import package to A (if missed, usually skipped)"
      include_tasks: include/import_package.yml
      vars:
        package_name: "{{ pkg_upgrade_R81 }}"
        logical_member: "{{ logicalAmember }}"
      when: pkg_index | int == 0


    - name: "Get pkg_index on B"
      include_tasks: include/get_pkg_index.yml
      vars:
        package_file_name: "{{ pkg_upgrade_R81 }}"
        logical_member: "{{ logicalBmember }}"

    - name: "Import package to B (if missed, usually skipped)"
      include_tasks: include/import_package.yml
      vars:
        package_name: "{{ pkg_upgrade_R81 }}"
        logical_member: "{{ logicalBmember }}"
      when: pkg_index | int == 0
