---
# Step 19 - Install policy to all members
# 1) Query GW for policy_name
# 2) Make changes on MDS
- name: "Step 19 - Get policy from SMO"
  gather_facts: false
  hosts: sg

  tasks:

    - name: "Timestamp / Start Step 19 - Get policy from SMO, Install policy to all members"
      include_tasks: ./include/print_datetime.yml
      when: loglevel>=2

    - name: "Get policy name"
      shell: "set -o pipefail && fw stat | tail -1 | awk '{ print $2 }'"
      register: policy_name
      changed_when: false

    - name: "Set policy name"
      set_fact:
        policy_name: "{{ policy_name.stdout }}"


- name: "Step 19 - Install policy to all members"
  hosts: mds
  gather_facts: false

  tasks:

    - name: "Set policy name"
      set_fact:
        policy_name: "{{ hostvars[groups.sg[0]]['policy_name'] }}"

    - name: "Set domain name"
      set_fact:
        domain_name: "{{ hostvars[groups.sg[0]]['domain_name'] }}"

    - name: "Set gateway name"
      set_fact:
        gw_name: "{{ hostvars[groups.sg[0]]['gw_name'] }}"

    - name: "Debug / Names"
      debug: msg="{{ policy_name }}@{{ gw_name }} in {{ domain_name }}"
      ignore_errors: true
      when: loglevel>0

    # - name: "Temporary stop"
    #   meta: end_play

# ! search for GW_NAME based on SMO ip, DMN, and fetch PACKAGE_NAME from GW

    - name: "Publish"
      shell: >
        mgmt_cli -u "{{ gui_user }}" -p "{{ gui_pass }}" --format json -d "{{ domain_name }}"
        publish
      changed_when: false
      register: res

    - name: "Installing policy"
      shell: >
        mgmt_cli -u "{{ gui_user }}" -p "{{ gui_pass }}" --format json -d "{{ domain_name }}"
        install-policy policy-package "{{ policy_name }}"
      changed_when: false
      register: res

    - name: "Debug / "
      debug:
        msg:
          - "{{ res.stdout_lines }}"
          - "Policy {{ policy_name }}@{{ domain_name }} is installed."
          - "Enjoy R81 on {{ gw_name }} :)"
      ignore_errors: true
      when: loglevel>1

    - name: "Debug / Restore smo image auto_clone on"
      debug:
        msg:
          - "Reminder: Restore 'smo image auto-clone state on' when needed for modules initially reported:"
          - "{{ auto_clone_smo }}"
      when: auto_clone_smo != ""
