---
- name: "Skyline"
  gather_facts: false
  serial: 1 # host after
  hosts: Skyline
  vars:
    jhf: Check_Point_R81_10_JHF_QA_MAIN_Bundle_T172_FULL.tar

  tasks:

gclish -c "show smo image auto-clone state"

    - name: "Prepare SG"
      block:
        - name: "lock database override" for SG
          shell: clish -c "lock database override"
          register: res
          changed_when: false
          failed_when:
            - "'CLICMD0201' not in res.stdout"

        - name: "Debug / lock database override (skyline.yml)"
          debug: msg="{{ res.stdout_lines }}"
          when: loglevel>=2


      when: type|default("") == "sg"

    - name: "Transfer package"
      block:
        - name: "Create local repo dir"
          file:
            path: "{{ local_repo }}"
            state: directory
            mode: 0777

        - name: "Transfer skyline JHF"
          copy:
            src: "{{ host_repo }}/{{ jhf }}"
            dest: "{{ local_repo }}"
            mode: 0644
      tags: transfer

    - name: "Import package"
      block:

        - name: "lock database override"
          shell: clish -c "lock database override"
          register: res
          changed_when: false
          failed_when:
            - "'CLICMD0201' not in res.stdout"

        - name: "Debug / lock database override (skyline.yml)"
          debug: msg="{{ res.stdout_lines }}"
          when: loglevel>=2

        - name: "Import package"
          shell: clish -c "installer import local {{ local_repo }}/{{ jhf }}"
          register: res
          changed_when: false
          ignore_errors: true

        - name: "Debug / Import package (skyline.yml)"
          debug: msg="{{ res.stdout_lines }}"
          when: loglevel>0

        - name: "Show packages"
          shell: clish -c "show installer packages"
          register: res
          changed_when: false
          ignore_errors: true

        - name: "Debug / Show packages (skyline.yml)"
          debug: msg="{{ res.stdout_lines }}"
          when: loglevel>0

        # - name: "Verify package"
        #   shell: clish -c "installer verify 1"
        #   register: res
        #   changed_when: false
        #   ignore_errors: true
      tags: import

    - name: "Install package"
      block:

        - name: "lock database override"
          shell: clish -c "lock database override"
          register: res
          changed_when: false
          failed_when:
            - "'CLICMD0201' not in res.stdout"

        - name: "Debug / lock database override (skyline.yml)"
          debug: msg="{{ res.stdout_lines }}"
          when: loglevel>=2

        - name: "Install package"
          shell: echo y | clish -c "installer install 1"
          register: res
          changed_when: false
          ignore_errors: true

        - name: "Debug / Verify package (skyline.yml)"
          debug: msg="{{ res.stdout_lines }}"
          when: loglevel>0
      tags: install



    - name: "Debug / Restore smo image auto_clone on"
      debug:
        msg:
          - "Reminder: Restore 'smo image auto-clone state on' when needed for modules initially reported:"
          - "{{ auto_clone_smo }}"
      when: auto_clone_smo != ""

# /opt/CPotelcol/config.yaml

    # - name: "Debug / "
    #   debug:
    #     msg:
    #       - "stdout_lines"
