---
- name: "Test"
  gather_facts: false
  hosts: sgt
  environment:
    BASH_ENV: /etc/profile

  tasks:

    - name: New SSH session
      meta: reset_connection

    - name: "Check"
      shell: |
        echo $PATH 
        which clish 
        which g_all 
        which jq
      ignore_errors: true
      register: res

    - name: "Debug / "
      debug:
        msg:
          - "stdout_lines"
          - "{{ res.stdout_lines|default('') }}"
          - "stderr_lines"
          - "{{ res.stderr_lines|default('') }}"
          - "{{ (ansible_env|default({})).PATH|default('') }}"


# [Expert@gw8020:0]# cat /home/admin/python
# #!/bin/bash
# /opt/CPsuite-R8*/fw1/Python/bin/python $*
